feat (core): add webpack config
Atzkdeff/react-js-2022q2 pull request #2
Opened 2022-05-31 09:41 UTC by Atzkdeff

2022-05-31 20:03 UTC, VladislavGordeyko requested changes

2022-05-31 20:03 UTC, VladislavGordeyko commented on webpack.config.js
> +        extensions: [".js"],
It's better to fix the webpack config to work with JSX file types. You can check here - https://stackoverflow.com/questions/46169472/reactjs-js-vs-jsx

2022-05-31 20:03 UTC, VladislavGordeyko commented on webpack.config.js
> +                exclude: /nodeModules/,
node_modules*

2022-05-31 21:46 UTC, Atzkdeff commented on webpack.config.js
> +        extensions: [".js"],
Fixed

2022-05-31 21:46 UTC, Atzkdeff commented on webpack.config.js
> +                exclude: /nodeModules/,
Fixed

2022-06-01 07:11 UTC, VladislavGordeyko approved these changes

2022-06-08 06:46 UTC, merged